const data = [
  {
    ID: 1,
    Name: "John Smith",
    Age: 25,
    Occupation: "Engineer",
    "Father's ID": 8,
  },
  {
    ID: 2,
    Name: "Sarah Johnson",
    Age: 32,
    Occupation: "Teacher",
    "Father's ID": 14,
  },
  {
    ID: 3,
    Name: "Michael Brown",
    Age: 41,
    Occupation: "Doctor",
    "Father's ID": 2,
  },
  {
    ID: 4,
    Name: "Emily Davis",
    Age: 28,
    Occupation: "Lawyer",
    "Father's ID": 10,
  },
  {
    ID: 5,
    Name: "David Wilson",
    Age: 35,
    Occupation: "Architect",
    "Father's ID": 9,
  },
  {
    ID: 6,
    Name: "Jennifer Thompson",
    Age: 29,
    Occupation: "Software Developer",
    "Father's ID": 14,
  },
  {
    ID: 7,
    Name: "Christopher Martinez",
    Age: 37,
    Occupation: "Accountant",
    "Father's ID": 5,
  },
  {
    ID: 8,
    Name: "Amanda Anderson",
    Age: 45,
    Occupation: "Nurse",
    "Father's ID": 3,
  },
  {
    ID: 10,
    Name: "Stephanie Clark",
    Age: 27,
    Occupation: "Marketing Manager",
    "Father's ID": 4,
  },
  {
    ID: 11,
    Name: "Matthew Rodriguez",
    Age: 39,
    Occupation: "Research Scientist",
    "Father's ID": 6,
  },
  {
    ID: 12,
    Name: "Samantha Lewis",
    Age: 33,
    Occupation: "Graphic Designer",
    "Father's ID": 13,
  },
  {
    ID: 13,
    Name: "Andrew Lee",
    Age: 26,
    Occupation: "Data Analyst",
    "Father's ID": 7,
  },
  {
    ID: 14,
    Name: "Lauren Hall",
    Age: 34,
    Occupation: "Financial Analyst",
    "Father's ID": null,
  },
];

export default data;
